//
//  AudioResponse.swift
//  OpenAI
//
//  Created by Firdavs Khaydarov on 02/08/2025.
//

public struct AudioResponse: Codable, Sendable {
    /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
    let data: String

    /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
    let expiresAt: Int

    /// Unique identifier for this audio response.
    let id: String

    /// Transcript of the audio generated by the model.
    let transcript: String
}
