name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'

jobs:
  macos-15:
    name: Build macOS 15
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    # - name: Run tests
    #   run: swift test -v
  ubuntu:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    # - name: Run tests
    #   run: swift test -v